Bastau/Enigmath/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from accounts.views import (login_view, register_view, logout_view)
from main.views import(main_view)

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^news/', include("news.urls", namespace='news')),
    url(r'^profile/', include("accounts.urls", namespace='accounts')),
    url(r'^olympiads/', include("olymps.urls", namespace='olymps')),
    url(r'^problems/', include("problems.urls", namespace='problems')),
    url(r'^courses/', include("courses.urls", namespace='courses')),
    url(r'^lectures/', include("lectures.urls", namespace='lectures')),
    url(r'^', include("main.urls", namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bastau/main/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    main_view,
    contacts_view,
    )

app_name = 'Enigmath'
urlpatterns = [
    url(r'^$', main_view, name='home'),
    url(r'^contacts/$', contacts_view, name='contacts'),
]

Bastau/news/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	news_list,
	news_create,
	news_detail,
	news_update,
	news_delete,
	)

app_name = 'Enigmath'
urlpatterns = [
	url(r'^$', news_list, name='list'),
    url(r'^create/$', news_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', news_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', news_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', news_delete, name='delete'),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

Bastau/problems/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    problem_thread,
    problem_delete

    )

app_name = 'Enigmath_problems'
urlpatterns = [
    url(r'^(?P<id>\d+)/$', problem_thread, name='thread'),
    url(r'^(?P<id>\d+)/delete/$', problem_delete, name='delete'),
]

Bastau/main/models.py
from django.db import models

# Create your models here.

Bastau/problems/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.text import slugify
from markdown_deux import markdown
from django.utils.safestring import mark_safe
from transliterate import translit, get_available_language_codes

from django.urls import reverse

from django.db import models
from django.contrib.postgres.fields import HStoreField
from django.contrib.postgres.fields import ArrayField

from accounts.models import Profile


# Create your models here.\


class ProblemManager(models.Manager):
    def all(self):
        return super(ProblemManager, self)

    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return super(ProblemManager, self).filter(content_type=content_type, object_id= instance.id)

    def filter_by_author(self, author):
        return super(ProblemManager, self).filter(user=author)


class Problem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete = models.PROTECT)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null = True)
    object_id = models.PositiveIntegerField(null = True)
    content_object = GenericForeignKey('content_type', 'object_id')

    content = models.TextField()
    title = models.CharField(max_length=120)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ProblemManager()

    class Meta:
        ordering = ['timestamp']

    def __unicode__(self):
        return str(self.user.username)

    def get_absolute_url(self):
        return reverse("problems:thread", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("problems:delete", kwargs={"id": self.id})
    
    def get_profile(self):
        return reverse("accounts:profile", kwargs={"user":self.user})
    def get_markdown(self):
        return mark_safe(markdown(self.content))



class CheckProblem(models.Model):
    user = models.PositiveIntegerField(null = True)
    problem_id = models.PositiveIntegerField(null = True)
    actions = ArrayField(ArrayField(models.TextField()), default=[['first', 'first_hidden']])
    solved = models.BooleanField(default=False) 

class Lemma(models.Model):
    name = models.TextField(default='de')

Bastau/problems/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Problem
from django.forms import CharField


class CreateProblemForm(forms.ModelForm):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    content = forms.CharField(widget=PagedownWidget(show_preview = False))
    class Meta:
        model = Problem
        fields = [
            "title",
            "content",
        ]

Bastau/main/views.py
from django.shortcuts import render, redirect
from accounts.models import Profile





def main_view(request):
    profile = 'admin'
    if request.user.is_authenticated:
        profile = Profile.objects.get(user = request.user.id)
    
    staff = "no"
    if request.user.is_staff or request.user.is_superuser:
        staff = "yes"
    context = {
    	"staff":staff,
	    "user":request.user,
        "profile":profile,
    }
    return render(request, "main.html", context)


def contacts_view(request):
    profile = 'admin'
    if request.user.is_authenticated:
        profile = Profile.objects.get(user = request.user.id)
    
    staff = "no"
    if request.user.is_staff or request.user.is_superuser:
        staff = "yes"
    context = {
        "staff":staff,
        "user":request.user,
        "profile":profile,
    }
    return render(request, "contacts.html", context)

Bastau/problems/views.py
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render, get_object_or_404

from accounts.models import Profile
from .solve_problem_form import SaveProblemForm

from .expression_form import ExpressionForm
from .models import Problem, CheckProblem, Lemma

from olymps.models import Olymp
# from lemmas.isequal import isequal, iseven, part1
from lemmas.codes import LemmaCode



def problem_delete(request, id):
    try:
        obj = Problem.objects.get(id=id)
    except:
        raise Http404

    if obj.user != request.user:
        reponse.status_code = 403
        return HttpResponse("You do not have permission to do this.")

    if request.method == "POST":
        parent_obj_url = obj.content_object.get_absolute_url()

        for checkprblm in CheckProblem.objects.filter(problem_id = obj.id):
            checkprblm.delete()

        obj.delete()
        messages.success(request, "This has been deleted.")
        return HttpResponseRedirect(parent_obj_url)
    
    profile = 'admin'
    if request.user.is_authenticated:
        profile = Profile.objects.get(user = request.user.id)
    staff = "no"

    if request.user.is_staff or request.user.is_superuser:
        staff = "yes"

    context = {
        "staff":staff,
        "profile":profile,
        "object": obj,
    }
    return render(request, "confirm_delete.html", context)

def problem_thread(request, id):
    try:
        obj = Problem.objects.get(id=id)
    except:
        raise Http404

    content_object = obj.content_object 
    content_id = obj.content_object.id
    initial_data = {
            "content_type": obj.content_type,
            "object_id": obj.object_id
    }
    if request.user.id:
        check_problem = CheckProblem.objects.get(problem_id = obj.id, user = request.user.id)
    else:
        messages.warning(request, "You need to authanticate to see problems")
        return HttpResponseRedirect(obj.content_object.get_absolute_url())
    
    expression_form = ExpressionForm(request.POST or None)
    save_problem_form = SaveProblemForm(request.POST or None)
    expr1 = ''
    expr2 = ''
    action_check = ''
    action_check2 = ''

    if len(check_problem.actions) > 0:
        if check_problem.actions[0][1] == 'first_hidden':
            check_problem.actions.pop(0) 
            check_problem.save()
    if expression_form.is_valid():
        expr_id = expression_form.cleaned_data.get('exp_id')-1
        if 'delete' in request.POST:
            check_problem.actions.pop(expr_id) 
            check_problem.save()
            return HttpResponseRedirect(obj.get_absolute_url())
        if 'use' in request.POST:
            init_data = {
                'expr2': check_problem.actions[expr_id][0]
            }
            save_problem_form = SaveProblemForm(request.POST or None, initial = init_data)
        
    if save_problem_form.is_valid():
        expr1 = save_problem_form.cleaned_data.get('expr1')
        expr2 = save_problem_form.cleaned_data.get('expr2')
        for i in range (0, len(Lemma.objects.filter())):
            if action_check == "Correct" and action_check2 == "Correct":
                break
        if expr1 != '':    
            action_check =  getattr(LemmaCode, Lemma.objects.filter()[i].name)(expr1)
        if expr2 != '':
            action_check2 = getattr(LemmaCode, Lemma.objects.filter()[i].name)(expr2)
        all_solved = True
        for actn in check_problem.actions:
            if actn[1] == 'Need to prove':
                if actn[0] != expr1 and actn[0] != expr2:
                    all_solved = False
        
        if all_solved == True:
            check_problem.solved = True
            check_problem.save()
                                        
        if 'save' in request.POST:
            if action_check != '':
                check_problem.actions.append([expr1, action_check])
                check_problem.save()
                return HttpResponseRedirect(obj.get_absolute_url())  
            elif action_check2 != '':
                check_problem.actions.append([expr2, action_check2])
                check_problem.save()
                return HttpResponseRedirect(obj.get_absolute_url()) 
    
    profile = 'admin'
    if request.user.is_authenticated:
        profile = Profile.objects.get(user = request.user.id)
    staff = "no"
    if request.user.is_staff or request.user.is_superuser:
        staff = "yes"
    
    context = {
        "staff":staff,
        "profile":profile,
        "problem": obj,
        "save_problem_form": save_problem_form,
        "check_problem": check_problem,
        "action_check":action_check,
        "expression_form": expression_form,
    }
    return render(request, "problem.html", context)

Bastau/templates/base.html
{% load staticfiles %}
<!--DOCTYPE html -->
<html>
<head>
	<meta charset="utf-8">
	<title>{% block head_title %}Bastau Academy{% endblock head_title %}</title>


	
	<!-- CSS -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,500&amp;subset=cyrillic" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href='{% static "css/semantic.min.css" %}'>
	<link rel='stylesheet' href='{% static "css/base.css" %}' />
	<link rel="icon" href='{% static "images/favicon.ico" %}' type="image/png">
	

	
	<link href="https://fonts.googleapis.com/css?family=Anton|Francois+One|Kanit|Oswald" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Changa:800|Montserrat:900" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>


	<script src='{% static "js/semantic.min.js" %}'></script>


	<style>
		{% block style %}{% endblock style %}
	</style>
	{% block head_extra %} {% endblock head_extra %}
</head>

<body>
	<div class="big-header">
		<div class="ui container">
			<div class="ui header-logo">
				<br>
				<div class="ten wide column oneline">
					<a href='{% url "main:home" %}' class="logo">Bastau Academy</a> 
				</div>
				<div class="right">
					<a class="target target-olymps" href='{% url "olymps:list" %}' >
						Olympiads
					</a>
					<a class="target target-ratings spacex2" href='{% url "news:list" %}'>
						Ratings
					</a>
					<a class="target target-news spacex2" href='{% url "news:list" %}'>
						News
					</a>
					<a class="target target-courses spacex2" href='{% url "courses:list" %}'>
						Learn
					</a>
					{% if request.user.is_authenticated %}	
						<a class="target target-profile spacex2"  href='{{ profile.get_absolute_url }}'><i class="fas fa-user"></i> {{ user }}</a>
						<a class="target spacex2" href='{% url "logout" %}'><i class="fas fa-sign-out-alt"></i> Logout</a>
					{% else %}
						<a class="target spacex2" href='{% url "login" %}'><i class="fas fa-sign-in-alt"></i> Login</a>
						<a class="target spacex2" href='{% url "register" %}'><i class="fas fa-user-plus"></i> Sign up</a>
					{% endif %}	
				</div>

			</div>
		</div>
	</div>
			
		





	{% include "messages_display.html" %}
	<div class='content-container'>
		{% block content %}{% endblock content %}
	</div>


	<div class="ui inverted vertical footer segment">
			<div class="ui center aligned container">
				<div class="ui stackable inverted divided grid">
					<div class="seven wide column">
						<h4 class="ui inverted header">Start from yourself</h4>
						<p class="white">Your motivation creates a great opportunity to be on the top of the world</p>
					</div>
					<div class="three wide column">
						<h4 class="ui inverted header">About</h4>
						<div class="ui inverted link list">
							<a href="#" class="item">News</a>
							<a href="#" class="item">Our team</a>
							<a href="#" class="item">Our supporters</a>
							<a href="#" class="item">Our contributors</a>
						</div>
					</div>
					<div class="three wide column">
						<h4 class="ui inverted header">Contacts</h4>
						<div class="ui inverted link list">
							<p href="#" class="item">Write us on mail</p>
							<a href="#" class="item">bastau@bastau.com</a>
						</div>
					</div>
					<div class="three wide column">
						<h4 class="ui inverted header">Subjects</h4>
						<div class="ui inverted link list">
							<a href="#" class="item">Math for silly</a>
							<a href="#" class="item">Math for old</a>
							<a href="#" class="item">Math for animals</a>
							<a href="#" class="item">Math for olympiads</a>
						</div>
					</div>
					
				</div>
				<div class="ui inverted section divider"></div>
				<div class="logo-footer centered">BASTAU<br>academy</div>
				<div class="ui horizontal inverted small divided link list">
					<a class="item" href="#">Site Map</a>
					<a class="item" href="#">Contact Us</a>
					<a class="item" href="#">Terms and Conditions</a>
					<a class="item" href="#">Privacy Policy</a>
				</div>
			</div>
		</div>



	




	<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

	<script src='{% static "js/jquery.min.js" %}' type="text/javascript"></script>

	<script src='{% static "js/semantic.min.js" %}' type="text/javascript"></script>


	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

	
	<script src='{% static "js/myscript.js" %}' type="text/javascript"></script>
	<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>

	<script type="text/javascript" src="https://vk.com/js/api/share.js?95" charset="windows-1251"></script>

	<script>(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = 'https://connect.facebook.net/ru_RU/sdk.js#xfbml=1&version=v2.12';
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

	<script>
		$('.ui .item').on('click', function() {
		      $('.ui .item').removeClass('active');
		      $(this).addClass('active');
		   }); 
	</script>



	<script type="text/javascript">
		$(document).ready(function(){
			$(".content-markdown").each(function(){
				var content = $(this).text()
				var markedContent = marked(content)
				$(this).html(markedContent)
			})
			$(".post-detail-item img").each(function(){
				$(this).addClass("img-responsive");
			})
			var contentInput = $("#id_content");
			function setContent(value){		   
				$("#preview-content").html(marked(value))
				$("#preview-content img").each(function(){
					$(this).addClass("img-responsive")
				})
			}
			setContent(contentInput.val())
			contentInput.keyup(function(){
				var newContent = $(this).val()
				setContent(newContent)
			})
			var titleInput = $("#id_title");
			function setTitle(value) {
				$("#preview-title").text(value)
			}
			setTitle(titleInput.val())
			titleInput.keyup(function(){
				var newContent = $(this).val()
				setTitle(newContent)
			})
			$(".comment-reply-btn").click(function(event){
				event.preventDefault();
				$(this).parent().next(".comment-reply").fadeToggle();
			})
			$(".comment-children-reply-btn").click(function(event){
				event.preventDefault();
				$(this).parent().next(".comment-reply").fadeToggle();
			})
		})
	</script>




</body>
</html>

Bastau/templates/course_list.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}
{% block content %}
<style type="text/css">
    .target-courses{
        color: #ff7477 !important;
    }
</style>


<div class='ui container'>
    <div class="ui grid">
        <div class=" twelve wide column">
            <h1>{{ title }}</h1>
                {% if staff == "yes" %}
                <h3 style="color: red"> Staff only: <a class="ui button red" href='{% url "courses:create" %}' >Create Course</a></h3>
            {% endif %}
        </div>
        <div class='four wide column'>
            <form method='GET' action=''>
                <div class="ui action input">
                    <input type='text' name='q' placeholder='Search courses' value='{{ request.GET.q }}'/>
                    <button class="ui button" type="submit">Search</button>
                </div>
            </form>
        </div>
        {% for obj in array_of_user %}
            <div class="ui segment" style="width:70%;">
                {% if obj.0.draft %}<h4 style="color: red">Staff only: Draft</h4>{% endif %} {% if obj.0.publish > today %}<h4>Staff Only: Future Course</h4>{% endif %}
                <!-- {% if obj.image %}  
                    <a class="oneline" href='{{ obj.get_absolute_url }}'><img class="olymp-image" src='{{ obj.image.url }}'/></a>
                {% endif %} -->
                    <h2 class="oneline"><a class="post-title" href='{{ obj.0.get_absolute_url }}'>{{ obj.0.title }}</a> </h2>
                    <h1 style="color: gold" class="oneline spacex2"> 
                        {% if obj.1.passed == 0 %}
                            <i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                        {% endif %}
                        {% if obj.1.passed == 1 %}
                            <i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                        {% endif %}
                        {% if obj.1.passed == 2 %}
                            <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i>
                        {% endif %}
                        {% if obj.1.passed  == 3 %}
                            <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
                        {% endif %}
                    </h1>
                <h5 class=" ">Level: 
                {% if obj.0.level == 1 %}
                    <a href="">Easy</a>
                {% endif %}
                {% if obj.0.level == 2 %}
                    <a href="">Middle</a> 
                {% endif %}
                {% if obj.0.level == 3 %}
                    <a href="">Hard</a>
                {% endif %}
                </h5>
                
                <h5 class="" style="margin-top: 5px;">{{ obj.0.content|truncatechars_html:200 }}</h5>
                {% if staff == "yes" %}
                    <a class="" href='{{ obj.0.get_update_url }}'>Edit</a>
                    <a href='{{ obj.0.get_delete_url }} ' style="color: red;" class="space">Delete</a>
                {% endif %}
            </div>
        {% endfor %}
    </div>





    <div class="pagination">
        <br><br><br>
        <span class="step-links">
            {% if object_list.has_previous %}
                <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
            </span>

            {% if object_list.has_next %}
                <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
            {% endif %}
        </span>
    </div>




</div>



{% endblock content %}

Bastau/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class='ui container'>
	<div class="ui one column centered grid">
		<div class="column">

			<h1>{{ title }}</h1>
			<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
				{{ form|crispy }}
				<input type='submit' class='ui button green'style="margin-top:20px" value='{{ title }}' />
			</form>

		</div>
	</div>

</div>
{% endblock content %}

Bastau/templates/news_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}


{% block content %}
<style type="text/css">
    .target-news{
        color: #ff7477 !important;
    }
</style>

<div class='ui container'>
    <div class="ui list">
        <a class="button ui blue" href='{% url "news:list" %}'>
            <i class="fas fa-chevron-circle-left"></i> Back to list
        </a>
        {% if staff == "yes" %}
        <h3 style="color: red;"> Staff only: <a class="button ui green" href='{% url "news:create" %}'>Create Post</a></h3>
        {% endif %}

        <h1>{{ title }}</h1>
        <h3>Created:<small>{{ instance.publish }}</small>
        </h3>


        <h4>Author: <a href="{{ instance.get_author }}">{{ instance.user.username }}</a></h4>

        {% if staff == "yes" %}
        <a href='{{ instance.get_update_url }}' class="">Edit</a> |
        <a href='{{ instance.get_delete_url }}' style="color: red;" class="space">Delete</a>
        {% endif %}

        <div class='row'>
            <div class='col-sm-12'>
                {{ instance.get_markdown }}
                {% if instance.image %}
                <img src='{{ instance.image.url }}'/>
                {% endif %}


            </div>
        </div>



        <div>
            <p class='lead'>
                {{ comments.count }} Comment{% if comments.count > 1 or comments.count == 0 %}s{% endif %}
            </p>
            {% if is_auth == False %}
            Please, <a href='{% url "login" %}'>login</a> to comment
            {% endif %}

            {% for comment in comments_parents %}


                {% if comment.author.image %}
                <a href="{{ comment.get_profile }}">
                    <img class="user_img_comments" src="{{ comment.author.image.url }}">
                </a>
                {% endif %}


                <a href="{{ comment.get_profile }}">
                    {{ comment.user }}
                </a>
                <p>{{ comment.content }}</p>
                <div class="small-details" style="margin-bottom:20px">
                    {{ comment.timestamp|timesince }} ago
                    {% if is_auth == True %}
                    <a class='button ui green' href='#'>
                        Reply
                    </a>
                    {% endif %}
                    {% if request.user == comment.user or staff == "yes" %}  <a href='{{ comment.get_delete_url }}' class="ui red button">Delete</a>
                    {% endif %}
                </div>
                {% if is_auth == True %}
                <div class='comment-reply'>
                    <form method="POST" action="." enctype="multipart/form-data"> {% csrf_token %}
                        {{ comment_form }}
                        <br><br>
                        <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                        <input type='submit' value='Reply' class='ui button green'>
                    </form>
                </div>
                {% endif %}

                {% for child_comment in comment.children %}

                    {% if child_comment.author.image %}
                    <a href="{{ child_comment.get_profile }}">
                        <img class="user_img_comments" src="{{ child_comment.author.image.url }}">
                    </a>
                    {% endif %}

                    <a href="{{ child_comment.get_profile }}">{{ child_comment.user }}</a>
                    <p>{{ child_comment.content }}</p>
                    <div class="small-details">{{ child_comment.timestamp|timesince }} ago
                        {% if is_auth == True %}
                        <a class='comment-children-reply-btn' href='#'>
                            | Reply
                        </a>
                        {% endif %}
                        {% if request.user == child_comment.user or staff == "yes"%}
                        | <a href='{{ child_comment.get_delete_url }}'>Delete</a>
                        {% endif %}
                    </div>
                    {% if is_auth == True %}
                    <div class='comment-reply'>
                        <form method="POST" action="."> {% csrf_token %}
                            {{ comment_form }}
                            <br><br>
                            <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                            <input type='submit' value='Reply' class='ui button green'>
                        </form>
                    </div>
                    {% endif %}
                {% endfor %}




            {% endfor %}
            {% if is_auth == True %}
            <form class="comment_form" method="POST" action='' enctype='multipart/form-data'> {% csrf_token %}
                {{ comment_form }}
                <br>
                <input type='submit' class='ui button green' value='Post comment'>
            </form>
            {% endif %}

        </div>
    </div>

</div>


{% endblock content %}

Bastau/templates/olymps_list.html
{% extends "base.html" %}
{% block content %}
<style type="text/css">
    .target-olymps{
        color: #ff7477 !important;
    }
</style>


<div class='ui container'>
    <div class="ui grid">
        <div class=" twelve wide column">
            <h1>{{ title }}</h1>
                {% if staff == "yes" %}
                <h3 style="color: red"> Staff only: <a class="ui button red" href='{% url "olymps:create" %}' >Create Olympiad</a></h3>
            {% endif %}
        </div>
        <div class='four wide column'>
            <form method='GET' action=''>
                <div class="ui action input">
                    <input type='text' name='q' placeholder='Search olympiads' value='{{ request.GET.q }}'/>
                    <button class="ui button" type="submit">Search</button>
                </div>
            </form>
        </div>
        {% for obj in object_list %}
            <div class="ui segment" style="width:70%;">
                {% if obj.draft %}<h4 style="color: red">Staff only: Draft</h4>{% endif %} {% if obj.publish > today %}<h4>Staff Only: Future Olympiad</h4>{% endif %}
                {% if obj.image %}
                    <a class="oneline" href='{{ obj.get_absolute_url }}'><img class="olymp-image" src='{{ obj.image.url }}'/></a>
                {% endif %}
                <div class="oneline">
                    <h3 class="oneline spacex2"><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a> </h3>
                    {% if staff == "yes" %}
                        <a class="spacex2" href='{{ obj.get_update_url }}'>Edit</a> |
                        <a href='{{ obj.get_delete_url }}'>Delete</a>
                    {% endif %}
                    <h5 class="oneline spacex2">Start: <a href="">{{ obj.start_time }}</a></h5>
                    <p class="oneline spacex2">Authors: <a href="{{ obj.get_author }}">{{ obj.user.username }}</a> </p>
                </div>
            </div>
        {% endfor %}
</div>





    <div class="pagination">
        <span class="step-links">
            {% if object_list.has_previous %}
                <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
            </span>

            {% if object_list.has_next %}
                <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
            {% endif %}
        </span>
    </div>




</div>



{% endblock content %}